version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/tonyjemba.com:/etc/nginx/sites-enabled/tonyjemba.com
      - ./nginx/default:/etc/nginx/sites-enabled/default
    depends_on:
      - portfolio
    

  portfolio:
    build: ./my-website
    container_name: portfolio
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
    ports:
      - '3000:3000'


