version: '3.8'

services:
  devnginx:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    container_name: devnginx
    restart: always
    tty: true
    ports:
      - '8092:80'
    volumes:
      - ./error.log:/var/log/nginx/error.log
      - ./dev.onlinepharmacy.tonyjemba.conf:/etc/nginx/conf.d/default.conf
      - ../onlinePharmacy/:/var/www/html/onlinePharmacy/
      - dev_sharedfilestorage:/var/www/html/onlinePharmacy/storage/app/public
      - dev_sharedfilestorage:/var/www/html/onlinePharmacy/public/storage/
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - devportfolio


networks:
  devportfolio:
    external: true

volumes:
  dev_sharedfilestorage:
    external: true