version: '2'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '8080:80'
      # - '443:443'
    depends_on:
      - portifolio
    # volumes:
    #   - /etc/letsencrypt/live/yourdomain.com/:/etc/letsencrypt/live/yourdomain.com/
    #   - /etc/letsencrypt/:/etc/letsencrypt
  portifolio:
    build: ./my-website
    container_name: portifolio
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
    ports:
      - '3000:3000'
    restart: always