version: '3.8'

services:

  jenkins:
    build: 
      context: ./
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jekins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - portfolio

volumes:
  jekins-data:

networks:
  portfolio:
    external: true
